"""
ZS CloudFront CDN session — stub that always returns None.

ZS Cloud inline images are served from cloudfront.tm4j.smartbear.com and require
a Forge JWT (generated by the ZS browser app). This token cannot be obtained via
any REST API — it is only issued by Atlassian's Forge runtime when the ZS app
runs in an authenticated browser session.

Consequence: inline images embedded in ZS objective/precondition HTML are NOT
downloaded. The migration preserves them as text notes in the form
``[Image: filename]`` so reviewers know they existed.

File attachments (uploaded via the Attachments tab) ARE migrated — they are
downloaded directly via the ZS REST API with the Bearer token.
"""


def get_cdn_cookie(config=None, logger=None) -> None:  # noqa: ARG001
    """Return None — CDN session acquisition is not supported without browser auth."""
    return None
